name: Update Language Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install PyGithub
      - name: Update stats
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          python - <<EOF
          from github import Github
          import os
          
          g = Github(os.getenv('GITHUB_TOKEN'))
          user = g.get_user('JhonaCodes')
          
          all_languages = ['Dart', 'Rust', 'Java', 'Kotlin']
          language_bytes = {lang: 0 for lang in all_languages}
          total_bytes = 0
          
          for repo in user.get_repos():
              try:
                  langs = repo.get_languages()
                  for lang, bytes_count in langs.items():
                      if lang in all_languages:
                          language_bytes[lang] += bytes_count
                          total_bytes += bytes_count
              except Exception as e:
                  print(f"Error processing repo {repo.name}: {e}")
          
          if total_bytes == 0:
              total_bytes = 1
              
          percentages = {lang: round((language_bytes[lang]/total_bytes)*100 if total_bytes > 0 else 0, 1) 
                        for lang in all_languages}
          
          filtered_languages = [lang for lang in all_languages if percentages[lang] >= 10]
          
          colors = {
              'Dart': '#00B4AB',
              'Rust': '#dea584',
              'Java': '#b07219',
              'Kotlin': '#A97BFF'
          }
          
          svg = f'''<?xml version="1.0" encoding="UTF-8"?>
          <svg xmlns="http://www.w3.org/2000/svg" width="300" height="165" viewBox="0 0 300 165">
              <!-- Card Background -->
              <rect width="300" height="165" rx="6" fill="#1a1b27"/>
              
              <!-- Title -->
              <text x="25" y="30" font-family="Arial" font-size="14" fill="#70a5fd">Lenguajes Recientes</text>
          '''
          
          y_position = 50
          for lang in filtered_languages:
              percentage = percentages[lang]
              bar_width = (percentage * 250) / 100
              
              svg += f'''
                  <g transform="translate(25, {y_position})">
                      <text x="0" y="0" font-family="Arial" font-size="12" fill="#38bdae">{lang}</text>
                      <text x="235" y="0" font-family="Arial" font-size="12" fill="#38bdae">{percentage}%</text>
                      <rect x="0" y="8" width="250" height="8" fill="#1f2133" rx="4"/>
                      <rect x="0" y="8" width="{bar_width}" height="8" fill="{colors[lang]}" opacity="0.7" rx="4"/>
                  </g>
              '''
              y_position += 35
          
          svg += '</svg>'
          
          with open('language-stats.svg', 'w') as f:
              f.write(svg)
              
          print("SVG created with filtered languages. Percentages:", {lang: percentages[lang] for lang in filtered_languages})
          EOF
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add language-stats.svg
          git commit -m "Update language stats" || exit 0
          git push
