name: Update Language Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install PyGithub
      - name: Update stats
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          python - <<EOF
          from github import Github
          import os
          
          g = Github(os.getenv('GITHUB_TOKEN'))
          user = g.get_user('JhonaCodes')
          
          # Mantener el orden completo pero filtrar después
          all_languages = ['Dart', 'Rust', 'Java', 'Kotlin']
          language_bytes = {lang: 0 for lang in all_languages}
          total_bytes = 0
          
          for repo in user.get_repos():
              try:
                  langs = repo.get_languages()
                  for lang, bytes_count in langs.items():
                      if lang in all_languages:
                          language_bytes[lang] += bytes_count
                          total_bytes += bytes_count
              except Exception as e:
                  print(f"Error processing repo {repo.name}: {e}")
          
          if total_bytes == 0:
              total_bytes = 1
              
          # Calcular porcentajes para todos
          percentages = {lang: round((language_bytes[lang]/total_bytes)*100 if total_bytes > 0 else 0, 1) 
                        for lang in all_languages}
          
          # Filtrar solo los que tienen más del 10%
          filtered_languages = [lang for lang in all_languages if percentages[lang] >= 10]
          
          colors = {
              'Dart': '#00B4AB',
              'Rust': '#dea584',
              'Java': '#b07219',
              'Kotlin': '#A97BFF'
          }
          
          # Ajustar altura del SVG según cantidad de lenguajes mostrados
          svg_height = 80 + (len(filtered_languages) * 40)
          
          svg = f'''<?xml version="1.0" encoding="UTF-8"?>
          <svg xmlns="http://www.w3.org/2000/svg" width="400" height="{svg_height}" viewBox="0 0 400 {svg_height}">
              <defs>
                  <linearGradient id="cardGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" style="stop-color:#1a1b27;stop-opacity:1" />
                      <stop offset="100%" style="stop-color:#242538;stop-opacity:1" />
                  </linearGradient>
                  <filter id="dropShadow">
                      <feGaussianBlur in="SourceAlpha" stdDeviation="2" />
                      <feOffset dx="0" dy="1" result="offsetblur" />
                      <feComponentTransfer>
                          <feFuncA type="linear" slope="0.2" />
                      </feComponentTransfer>
                      <feMerge>
                          <feMergeNode />
                          <feMergeNode in="SourceGraphic" />
                      </feMerge>
                  </filter>
              </defs>
              
              <rect width="400" height="{svg_height}" rx="15" fill="url(#cardGradient)" filter="url(#dropShadow)" />
              <text x="30" y="45" font-family="Arial" font-size="20" fill="#70a5fd" font-weight="bold">
                  Lenguajes utilizados recientemente.
              </text>
              <line x1="30" y1="60" x2="370" y2="60" stroke="#38bdae" stroke-width="0.5" opacity="0.3"/>
          '''
          
          y_position = 90
          for lang in filtered_languages:
              percentage = percentages[lang]
              bar_width = (percentage * 340) / 100
              
              svg += f'''
                  <g transform="translate(30, {y_position})">
                      <text x="0" y="0" font-family="Arial" font-size="14" fill="#fff">{lang}</text>
                      <text x="340" y="0" font-family="Arial" font-size="14" fill="#38bdae" text-anchor="end">{percentage}%</text>
                      <rect x="0" y="10" width="340" height="12" rx="6" fill="#1f2133" opacity="0.7"/>
                      <rect x="0" y="10" width="{bar_width}" height="12" rx="6" fill="{colors[lang]}">
                          <animate attributeName="width" from="0" to="{bar_width}" dur="1s" fill="freeze"/>
                      </rect>
                  </g>
              '''
              y_position += 40
          
          svg += '</svg>'
          
          with open('language-stats.svg', 'w') as f:
              f.write(svg)
              
          print("SVG created with filtered languages. Percentages:", {lang: percentages[lang] for lang in filtered_languages})
          EOF
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add language-stats.svg
          git commit -m "Update language stats" || exit 0
          git push
